---
# roles/packages/vars/main.yml

packages:
  archlinux:
    pacman:
      - tmux
      - htop
      - firefox
      - man-db
      - git
      - zsh
      - wget
      - curl
      - vim
      - jq
      - openssh
      - python
      - kubectl
      - kubectx
      - doctl
      - terraform
      - mpv
      - nvidia
      - nvidia-lts
      - tmux
      - github-cli
      - helm
      - signal-desktop
      - python-pipenv
      - pavucontrol
      - element-desktop
    aur:
      - visual-studio-code-bin
      - obsidian
      - flux-bin
      - gron
      - kind
      - bitwarden-bin
      - exodus
      - iota-firefly-wallet
