repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: no-commit-to-branch

  - repo: https://github.com/ansible-community/ansible-lint
    rev: v5.3.1
    hooks:
      - id: ansible-lint
        args:
          - --project-dir . -f pep8
