---
# arch-linux.yml

- hosts: localhost
  gather_facts: true

  tasks:
    - name: Install packages
      become: yes
      community.general.pacman:
        update-cache: yes
        name: "{{ item }}"
        state: present
      loop:
        - tmux
        - htop
        - firefox
        - man-db
        - git
        - zsh
        - wget
        - curl
        - rsync
        - networkmanager-openvpn
        - intel-ucode
        - gnome-firmware
        - linux-firmware
        - sof-firmware
        - fwupd
        - gnome-tweaks
        - networkmanager
        - os-prober
        - ttf-cascadia-code
        - ttf-fira-code
        - vim
        - wireless_tools
        - wpa_supplicant
        - dialog
        - dosfstools
        - efibootmgr
        - grub
        - gtk2
        - linux
        - linux-headers
        - linux-lts
        - linux-lts-headers
        - lvm2
        - mesa
        - netctl
        - base
        - mtools
        - sudo
        - jq
        - openssh
        - python
        - gnupg
        - pcsclite
        - ccid
        - hopenpgp-tools
        - yubikey-personalization

    - name: Install AUR packages
      community.general.pacman:
        name: "{{ item }}"
        state: present
        executable: paru
      loop:
        - visual-studio-code-bin
        - nerd-fonts-meslo
        - keyleds
        - obsidian
      tags:
        - aur

    - name: Add dvorak keyboard layout
      community.general.dconf:
        key: /org/gnome/desktop/input-sources/sources
        value: "[('xkb', 'us'), ('xkb', 'us+dvorak')]"
