---
# arch-linux.yml

- hosts: localhost
  gather_facts: true

  roles:
    - archlinux
    - thinkpad
    - gnome

  tasks:
    - name: Install packages
      become: yes
      community.general.pacman:
        update_cache: yes
        name: "{{ item }}"
        state: present
      loop:
        - tmux
        - htop
        - firefox
        - man-db
        - git
        - zsh
        - wget
        - curl
        - rsync
        - networkmanager-openvpn
        - ttf-cascadia-code
        - ttf-fira-code
        - vim
        - gtk2
        - jq
        - openssh
        - python
        - gnupg
        - pcsclite
        - ccid
        - hopenpgp-tools
        - yubikey-personalization

    - name: Install AUR packages
      community.general.pacman:
        name: "{{ item }}"
        state: present
        executable: paru
      loop:
        - visual-studio-code-bin
        - nerd-fonts-meslo
        - keyleds
        - obsidian
      tags:
        - aur
