---
# roles/arch-linux/tasks/main.yml

- name: install Arch Linux specific packages
  become: yes
  community.general.pacman:
    name: "{{ item  }}"
    state: present
    update_cache: yes
  loop: ["{{ packages.base }}"]

- name: set hostname to {{ hostname }}
  become: yes
  ansible.builtin.template:
    src: hostname.j2
    dest: /etc/hostname
    owner: root
    group: root
    mode: 0644

- name: set hosts file
  become: yes
  ansible.builtin.template:
    src: hosts.j2
    dest: /etc/hosts
    backup: yes
    owner: root
    group: root
    mode: 0644

- name: set default editor
  become: yes
  ansible.builtin.blockinfile:
    dest: /etc/profile
    marker_begin: EDITOR BEGIN
    marker_end: EDITOR END
    block: |
      # Set default editor
      EDITOR={{ user.editor }}

- name: pacman preferences
  import_tasks: pacman.yml
  tags: pacman

- name: install paru
  when: ansible_facts['os_family']|lower == 'archlinux'
  import_tasks: paru.yml
  tags:
    - aur
    - paru

- name: install network manager
  import_tasks: networkmanager.yml
  tags: networkmanager
