---
# roles/arch-linux/tasks/main.yml

- name: install Arch Linux specific packages
  become: yes
  community.general.pacman:
    name: "{{ item  }}"
    state: present
    update_cache: yes
  loop: "{{ packages }}"

- name: set hostname to {{ hostname }}
  become: yes
  ansible.builtin.template:
    src: hostname.j2
    dest: /etc/hostname
    owner: root
    group: root
    mode: "0644"
  tags: hostname

- name: set mirrorlist
  become: yes
  ansible.builtin.template:
    src: mirrorlist.j2
    dest: /etc/pacman.d/mirrorlist
    owner: root
    group: root
    mode: "0644"
