---
# roles/arch-linux/tasks/main.yml

- name: install Arch Linux specific packages
  become: yes
  community.general.pacman:
    name: "{{ item  }}"
    state: present
    update_cache: yes
  loop: "{{ packages.base }}"

- name: pacman preferences
  import_tasks: pacman.yml
  tags: pacman

- name: install network manager
  import_tasks: networkmanager.yml
  tags: networkmanager
