---
# roles/archlinux/tasks/paru.yml

- name: create aur_builer
  import_tasks: aur_builder.yml

- name: install paru
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    name: paru

- name: reverse order of paru output
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/paru.conf
    regexp: ^#BottomUp
    line: BottomUp

- name: use doas for privilege escalation
  become: yes
  ansible.builtin.blockinfile:
    path: /etc/paru.conf
    marker_begin: PRIVILEGE ESCALATION BEGIN
    marker_end: PRIVILEGE ESCALATION END
    block: |
      [bin]
      Sudo = doas
