---
# roles/autofs/tasks/archlinux.yml

- name: install autofs specific packages
  become: yes
  community.general.pacman:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: ["{{ packages.archlinux.pacman }}"]
  notify: enable rpcbind

- name: install autofs specific AUR packages
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    name: "{{ item }}"
    state: present
    use: paru
    aur_only: yes
  loop: ["{{ packages.archlinux.aur }}"]
  notify: enable autofs
