---
# roles/bluetooth/tasks/main.yml

- name: install packages for Arch Linux
  when: ansible_facts['os_family']|lower == 'archlinux'
  import_tasks: archlinux.yml

- name: enable bluetooth
  become: yes
  ansible.builtin.systemd:
    name: bluetooth
    state: started
    enabled: yes
