---
# roles/gnome/tasks/archlinux.yml

- name: install gnome specific packages
  become: yes
  community.general.pacman:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: ["{{ packages.gnome }}"]

- name: install gnome specific AUR packages
  become_user: aur_builder
  kewlfft.aur.aur:
    name: "{{ item }}"
    state: present
    use: paru
    aur_only: yes
  loop: ["{{ packages.aur }}"]

- name: install gnome packages applicable for Thinkpad X1 Carbon (Gen 8)
  become: yes
  when: ansible_facts['product_version'] == 'ThinkPad X1 Carbon Gen 8'
  community.general.pacman:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: ["{{ packages.thinkpad }}"]
