---
# roles/gnome/tasks/main.yml

- name: install packages for Arch Linux
  when: ansible_facts['os_family']|lower == 'archlinux'
  import_tasks: archlinux.yml

- name: enable user extensions
  community.general.dconf:
    key: /org/gnome/shell/disable-user-extensions
    value: "false"

- name: install gnome extensions
  ansible.builtin.include_role:
    name: jaredhocutt.gnome_extensions
  vars:
    gnome_extension_ids: "{{ gnome.extensions }}"

- name: add dvorak keyboard layout
  community.general.dconf:
    key: /org/gnome/desktop/input-sources/sources
    value: "[('xkb', 'us'), ('xkb', 'us+dvorak')]"

- name: set numlock on login
  community.general.dconf:
    key: /org/gnome/desktop/peripherals/keyboard/numlock-state
    value: "true"

- name: remember last state of numlock
  community.general.dconf:
    key: /org/gnome/desktop/peripherals/keyboard/remember-numlock-state
    value: "true"

- name: gnome terminal settings
  import_tasks: terminal.yml
  tags: terminal

- name: set profile picture
  become: yes
  ansible.builtin.copy:
    src: profile.png
    dest: "/var/lib/AccountsService/icons/{{ user.username }}"
    mode: 0644
