---
# roles/gnome/tasks/main.yml

- name: install gnome specific packages
  become: yes
  when: ansible_facts['os_family'] == 'Archlinux'
  community.general.pacman:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: "{{ packages.gnome }}"

- name: install gnome packages applicable for Thinkpad X1 Carbon (Gen 8)
  become: yes
  when: ansible_facts['product_version'] == 'ThinkPad X1 Carbon Gen 8' and ansible_facts['os_family'] == 'Archlinux'
  community.general.pacman:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: "{{ packages.thinkpad }}"

- name: Add dvorak keyboard layout
  community.general.dconf:
    key: /org/gnome/desktop/input-sources/sources
    value: "[('xkb', 'us'), ('xkb', 'us+dvorak')]"
