---
# roles/fancontrol/tasks/archlinux.yml

- name: install fancontrol specific packages
  become: yes
  community.general.pacman:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: ["{{ packages.archlinux.aur }}"]
