---
# roles/fancontrol/tasks/archlinux.yml

- name: install thinkfan specific packages
  become: yes
  community.general.pacman:
    name: "{{ item }}"
    state: present
    update_cache: yes
  when: ansible_facts['product_version'] == 'ThinkPad X1 Carbon Gen 8'
  loop: ["{{ packages.archlinux.aur }}"]
