---
# roles/yubikey/vars/main.yml

packages:
  yubikey:
    - gnupg
    - pcsclite
    - ccid
    - hopenpgp-tools
    - yubikey-personalization
    - yubikey-personalization-gui
    - yubioath-desktop
    - yubikey-manager
    - pcsclite
  archlinux:
    - gtk2

services:
  systemd:
    - pcscd
