---
# roles/thinkpad/tasks/archlinux.yml

- name: install Thinkpad X1 Carbon (Gen 8) specific packages
  become: yes
  when: ansible_facts['os_family']|lower == 'archlinux'
  community.general.pacman:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: ["{{ packages.archlinux }}"]
