---
# roles/thinkpad/tasks/main.yml

- name: install Thinkpad X1 Carbon (Gen 8) specific packages
  become: yes
  community.general.pacman:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: "{{ packages.archlinux }}"
