---
# roles/docker/tasks/archlinux.yml

- name: install docker specific packages
  become: yes
  community.general.pacman:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: ["{{ packages.docker }}"]
