---
# roles/doas/tasks/archlinux.yml

- name: install autofs specific packages
  become: yes
  community.general.pacman:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: ["{{ packages.archlinux.pacman }}"]
