---
# roles/lvm/tasks/archlinux.yml

- name: install lvm specific packages
  become: yes
  community.general.pacman:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: ["{{ packages.lvm }}"]
