name: linting

on:
  pull_request:

jobs:
  ansible-lint:
    name: ansible-lint
    runs-on: ubuntu-latest
    env:
      GITHUB_ACTIONS: true
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
          architecture: x64

      - name: install ansible-lint
        run: |
          python -m pip install --upgrade pip setuptools pipenv
          pipenv install --dev --system --ignore-pipfile

      - name: install ansible requirements
        run: |
          ansible-galaxy collection install --collections-path collections.galaxy --requirements-file requirements.yml
          ansible-galaxy role install --roles-path roles.galaxy --role-file requirements.yml

      - name: lint playbook
        run: ansible-lint

  prettier:
    name: prettier
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: prettier
        uses: creyD/prettier_action@v4.0
        with:
          prettier_options: --check .
