name: linting

on:
  pull_request:

jobs:
  ansible-lint:
    name: ansible-lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
          architecture: x64

      - name: install ansible-lint
        run: |
          python -m pip install --upgrade pip setuptools pipenv
          pipenv install --dev --system --ignore-pipfile

      - name: install ansible role dependencies
        run: ansible-galaxy role install --role-file roles/requirements.yml

      - name: install ansible collection dependencies
        run: ansible-galaxy collection install --requirements-file roles/requirements.yml

      - name: lint playbook
        run: ansible-lint --project-dir . -f pep8

  prettier:
    name: prettier
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: prettier
        uses: creyD/prettier_action@v4.0
        with:
          prettier_options: --check .
