name: Lint ansible playbook

on:
  push:
    branches: [main]

  pull_request:
    paths:
      - "distro.yml"
      - "roles/**/*.yml"
      - "**/workflows/*.yml"

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
          architecture: x64

      - name: install ansible-lint
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: install ansible roles
        run: ansible-galaxy install kewlfft.aur

      - name: lint playbook
        run: ansible-lint distro.yml -f pep8 --project-dir .
